/**
 * Created by Flowers博爵 on 2018/11/29.
 */
export const RECEIVE_DATA_HOME='RECEIVE_DATA_HOME'
export const RECEIVE_DATA_NAV='RECEIVE_DATA_NAV'
export const RECEIVE_DATA_TOPIC='RECEIVE_DATA_TOPIC'
export const RECEIVE_INDEX='RECEIVE_INDEX'
